// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: protos/sum_api.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type APIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integer1 int32 `protobuf:"varint,1,opt,name=integer1,proto3" json:"integer1,omitempty"`
	Integer2 int32 `protobuf:"varint,2,opt,name=integer2,proto3" json:"integer2,omitempty"`
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sum_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sum_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_protos_sum_api_proto_rawDescGZIP(), []int{0}
}

func (x *APIRequest) GetInteger1() int32 {
	if x != nil {
		return x.Integer1
	}
	return 0
}

func (x *APIRequest) GetInteger2() int32 {
	if x != nil {
		return x.Integer2
	}
	return 0
}

type APIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sum_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sum_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_protos_sum_api_proto_rawDescGZIP(), []int{1}
}

func (x *APIResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_protos_sum_api_proto protoreflect.FileDescriptor

var file_protos_sum_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x75, 0x6d, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x44,
	0x0a, 0x0a, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x32, 0x22, 0x25, 0x0a, 0x0b, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3a, 0x0a, 0x06, 0x53,
	0x75, 0x6d, 0x41, 0x50, 0x49, 0x12, 0x30, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_sum_api_proto_rawDescOnce sync.Once
	file_protos_sum_api_proto_rawDescData = file_protos_sum_api_proto_rawDesc
)

func file_protos_sum_api_proto_rawDescGZIP() []byte {
	file_protos_sum_api_proto_rawDescOnce.Do(func() {
		file_protos_sum_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_sum_api_proto_rawDescData)
	})
	return file_protos_sum_api_proto_rawDescData
}

var file_protos_sum_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_sum_api_proto_goTypes = []interface{}{
	(*APIRequest)(nil),  // 0: protos.APIRequest
	(*APIResponse)(nil), // 1: protos.APIResponse
}
var file_protos_sum_api_proto_depIdxs = []int32{
	0, // 0: protos.SumAPI.Sum:input_type -> protos.APIRequest
	1, // 1: protos.SumAPI.Sum:output_type -> protos.APIResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_sum_api_proto_init() }
func file_protos_sum_api_proto_init() {
	if File_protos_sum_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_sum_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_sum_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_sum_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_sum_api_proto_goTypes,
		DependencyIndexes: file_protos_sum_api_proto_depIdxs,
		MessageInfos:      file_protos_sum_api_proto_msgTypes,
	}.Build()
	File_protos_sum_api_proto = out.File
	file_protos_sum_api_proto_rawDesc = nil
	file_protos_sum_api_proto_goTypes = nil
	file_protos_sum_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumAPIClient is the client API for SumAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumAPIClient interface {
	Sum(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIResponse, error)
}

type sumAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSumAPIClient(cc grpc.ClientConnInterface) SumAPIClient {
	return &sumAPIClient{cc}
}

func (c *sumAPIClient) Sum(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIResponse, error) {
	out := new(APIResponse)
	err := c.cc.Invoke(ctx, "/protos.SumAPI/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumAPIServer is the server API for SumAPI service.
type SumAPIServer interface {
	Sum(context.Context, *APIRequest) (*APIResponse, error)
}

// UnimplementedSumAPIServer can be embedded to have forward compatible implementations.
type UnimplementedSumAPIServer struct {
}

func (*UnimplementedSumAPIServer) Sum(context.Context, *APIRequest) (*APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSumAPIServer(s *grpc.Server, srv SumAPIServer) {
	s.RegisterService(&_SumAPI_serviceDesc, srv)
}

func _SumAPI_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumAPIServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SumAPI/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumAPIServer).Sum(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SumAPI",
	HandlerType: (*SumAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumAPI_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sum_api.proto",
}
